### ISSUE TITLE
想问如何联系客服？

### ISSUE THREAD

**Issue by jesshew** [eudic/eudic_win32_localize#3]
你好，我是你们软件的忠实用户，日前看到你们有在举办终身免费VIP的活动所以参加了。
但由于我是外国用户，没有qq， 目前联系不了官方QQ号，不知道你们有微信 或则 官方电邮吗？我该如何联系你们领取终身免费VIP 呢？
![IMG_4819301C48BB-1](https://user-images.githubusercontent.com/44492141/118916089-dcf56200-b960-11eb-94f4-f7789b16dca7.jpeg)
![IMG_C1E2147B189C-1](https://user-images.githubusercontent.com/44492141/118916166-fd252100-b960-11eb-9d15-54cf396aaee0.jpeg)

我的[贴文](http://xhslink.com/lWidyc)目前已累计 

228赞，123收藏，已是兑奖额的10倍。
参加规则里并没有提及外国用户不能参加。希望你们能帮助我。

**Comment by bernardx** [comment]
可以通过邮件和我们联系 help@eudic.net
这里也有其他联系途径： https://www.eudic.net/v4/en/home/support
